### ISSUE TITLE
Safari rendering issue

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#67]
Safari on MacBook Pro not rendering the page in the Agipo typeface. Additionally, the borders have fallen off the tags. 

**Machine:** MacBook Pro (Retina, 13-inch, Early 2015)
**OS:** macOS Sierra Version 10.12 (16A323)
**Browser:** Version 10.0 (12602.1.50.0.10)

Typeface/tag rendering issue:
![safari-rendering-issue](https://user-images.githubusercontent.com/26731347/32308747-6e0851cc-bfc2-11e7-95e2-98b62080c6ff.jpg)

**Comment by rdunk** [comment]
Resolved the tag border issue but can't seem to replicate the incorrect font rendering issue. I've tested as far back as Safari 6.2 on Mountain Lion, font seems to render OK. Most likely a caching or network issue, can you check the network tab to see if the fonts are downloading correctly?

**Comment by chrismplus** [comment]
The fonts are now resolving correctly but the border issue persists with the tags from my side (unless you haven't pushed through the fix for them yet?)

**Agipo renders in--tags remain as is:**
![borderless-tags](https://user-images.githubusercontent.com/26731347/32357767-a4e9e616-c07a-11e7-90fd-5f87f925d9c0.png)

**Comment by chrismplus** [comment]
iOS Safari appears to be unaffected.

**Comment by rdunk** [comment]
I did indeed forget to push to the staging server before leaving yesterday, so most likely that's why you weren't seeing a fix.

Closing but please reopen if either problem persists.
